baseURL = "https://tsungyi.li/Blog"
languageCode = "en-us"
title = "終於明白 | tsungyi knows."
theme = "hugo-theme-m10c"
googleAnalytics = 'UA-1062546-8'
disqusShortname = 'tsungyi-li'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about.html"

[Params]
  author = "Li TsungYi"
  description = "Hi, I am Li Tsung-Yi (李宗沂). I am a game developer from 🇹🇼 Taiwan."
  avatar = "/images/Profile.jpg"
  menu_item_separator = " | "
  favicon = "/favicon.ico"

  [[params.social]]
    icon = "brand-github"
    name = "Github"
    url = "https://github.com/litsungyi"

  [[params.social]]
    icon = "brand-facebook"
    name = "Facebook"
    url = "https://www.facebook.com/litsungyi"

  [[params.social]]
    icon = "brand-linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/litsungyi"

  [params.style]
    darkestColor = "#2e3440"
    darkColor = "#434c5e"
    lightColor = "#d8dee9"
    lightestColor = "#eceff4"
    primaryColor = "#a3be8c"
